### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by ronen** [JanHalozan/iTunesConnectAnalytics#11]
Thanks for making this package!

Do you happen to have a link to any documentation for the API --  I.e. the return data format, fields, error conditions, etc.?  (My google-fu is failing me!)   Or is it undocumented/reverse-engineered?

**Comment by JanHalozan** [comment]
It's reverse-engineered. The best way to check errors and stuff is to `curl` and try to put stupid things in the payload to see what you get out :) Hope it helps.

**Comment by ronen** [comment]
Yep that's what I've been doing.  Thanks!
