### ISSUE TITLE
Account Switching

### ISSUE THREAD

**Issue by hugoduraes** [JanHalozan/iTunesConnectAnalytics#12]
On the web interface, we're able to do [account switching](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SettingUpUserAccounts.html#//apple_ref/doc/uid/TP40011225-CH25-SW103).

Is there a way to switch accounts using this module?

**Comment by JanHalozan** [comment]
Right now there is no option for that. A workaround would be to create multiple accounts. Seems reasonable to add it, but currently I'm quite busy. You can add the functionality and drop me a pull request or I can check it when I have time. Shouldn't bee too much of a problem. Probably just a matter of swapping the cookie.
