### ISSUE TITLE
No account cookie :( Apple probably changed the login process

### ISSUE THREAD

**Issue by rodrigowirth** [JanHalozan/iTunesConnectAnalytics#15]
When creating a new Itunes instance I got this error: _No account cookie :( Apple probably changed the login process_

Here is my code:
```
const instance = new Itunes(config.env.itunes.username, config.env.itunes.password, {
    errorCallback: (error) => {
      throw new BadRequestError(error);
    },
    successCallback: () => {
      console.log('Logged in');
    },
  });
```

I'm not sure how can I help with that.

**Comment by JanHalozan** [comment]
Can you provide the code on how you're using it? Are you sure that the username and password are correct. Tried it myself and it's working.

**Comment by rodrigowirth** [comment]
Sorry, I have just figured out that the password was wrong. Maybe we can improve the error message.

**Comment by JanHalozan** [comment]
Yeah we could do that. You can open a new issue for that.
