### ISSUE TITLE
Error logging in: Error: No account cookie :( Apple probably changed the login process

### ISSUE THREAD

**Issue by th0ress0n** [JanHalozan/iTunesConnectAnalytics#17]
This issue is persistent. I have verified that it is not a credentials issue. I have been able to access ITC. 
I am getting the same issue when using the default password as well as using the app-specific password. Appreciate any help with this.

**Comment by JanHalozan** [comment]
What do you mean by default or app specific password? The username and password should be the same as the credentials you use to log in into iTC. I've tried it myself and it's working on my side. So I'll need a bit more info from you in order to see what's up.

**Comment by th0ress0n** [comment]
The default password is the password used for authentication towards itunesconnect portal. Using these credentials whilst having two-factor enabled fails with the message 
"Error logging in: Error: No account cookie :( Apple probably changed the login process"
But will send a two-factor event.

Using the app-specific password that i have generated for my account on https://appleid.apple.com/ will also give the above error message whilst not trigger a two-factor authentication session.

**Comment by JanHalozan** [comment]
I see. The issue is with two factor authentication. This library does currently not support two factor auth. A workaround is to create a separate user (for which you can enable only analytics) and use that one for collecting data.

**Comment by th0ress0n** [comment]
![itunesconnectanalytics](https://user-images.githubusercontent.com/7384556/28112012-890f10ea-6708-11e7-97e0-896d8463bc88.png)
Disabling the two factor authentication worked perfectly, thanks for your help.
