### ISSUE TITLE
bug: group metric taking first char

### ISSUE THREAD

**Issue by Nivgov** [JanHalozan/iTunesConnectAnalytics#18]
I noticed that if you use the the group option with 1 metric, it takes the first char as group metric.
for example:
```
options = {
  measures:itc.measures.units,
  group: {
    dimension: itc.dimension.territory
  }
}
```
will result in:
```
"errors": [
      {
         "message": "Invalid measure: u"
      }
   ]
```
It happens because the query initialization happens before the assembleBody function, that puts the measures in an array.

**Comment by JanHalozan** [comment]
Can you fix it and submit a PR? Can do it myself but will take some time.

**Comment by Nivgov** [comment]
Yeah I can try tomorrow or on Sunday, if I'll have the time.
