### ISSUE TITLE
node-itunesconnect pointing now to this repo

### ISSUE THREAD

**Issue by stoprocent** [JanHalozan/iTunesConnectAnalytics#21]
Hi @JanHalozan 

Since I didn't update my [node-itunesconnect](https://github.com/stoprocent/node-itunesconnect) tool in years and I'm cleaning my github account I've asked anyone interested to use your great tool. . 

I hope it's ok with you.

Regards

M

**Comment by JanHalozan** [comment]
Yes it's perfectly ok. You're welcome to use this package and drop a PR if you ever find an issue :)
