### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by ChaosCoder** [JanHalozan/iTunesConnectAnalytics#3]
Querying e.g. the last 7 days (e.g. units, sales) should only return the days for which Apple provided data. 

Currently, the last days always have a value of 0, making it hard to distinguish if the value is really zero or if the data is not yet available.

Is there any API to accomplish that?

**Comment by JanHalozan** [comment]
Fixed and released `0.2.4` version. Thank you.

I have added a new method to the `Itunes` connect class which allows you to get settings which contain the data end date. Use that date in your queries to avoid getting zeroes. View [readme](https://github.com/JanHalozan/iTunesConnectAnalytics/blob/master/README.md) for more info (search for `instance.getSettings`).

Make sure to update your version to `0.2.4`. Let me know if it works.
