### ISSUE TITLE
Race condition causes Invalid iTC User Role

### ISSUE THREAD

**Issue by ronnessim** [JanHalozan/iTunesConnectAnalytics#32]
Running a simple test.js like this (copied from examples):

```
var itc = require('itunesconnectanalytics');
var Itunes = itc.Itunes;
var AnalyticsQuery = itc.AnalyticsQuery;

var username = 'xxxxxxxx'; //REAL USERNAME AND PW REMOVED
var password = 'yyyyyyyy';

var appId = '12345'; //Found in My Apps -> App -> Apple ID or read below on gett
ing the app id.

var instance = new Itunes(username, password, {
  errorCallback: function(e) {
    console.log('Error logging in: ' + e);
  },
  successCallback: function(d) {
    console.log('Logged in');
  }
});

instance.getApps(function(error, data) {
  console.log(JSON.stringify(data, null, 2));
});
```

When I run this from the command line, I get inconsistent results. Some requests return the expected result (which confirms the roles are set up correcting in iTC). Also note that I consistently get the same server IP from apple/akamai, but some percentage of requests result in this error:

```
{
  "itcBaseUrl": "https://appstoreconnect.apple.com",
  "message": "Invalid iTC User Role",
  "l10n": {
    "Crossfire-response-invalidrole-message": "If you think you should have access to App Analytics, contact your iTunes Connect user with the admin role.",
    "Crossfire-response-invalidrole-link": "iTunes Connect Homepage",
    "Crossfire-response-invalidrole-title": "You don’t have access to App Analytics."
  },
  "redirectUrl": "/"
}
```

Other details : 

NodeJS version: v6.11.3 (bundled with OS) and node v8.11.4 (latest) produce the same result.
OS version: RHEL 7.5. One theory is that their might be a race condition inside the library which produces different a different result based on the order of execution.

**Comment by omatty198** [comment]
I also face the same issue. but when I changed from 'Developer' to 'Sales' role, resolved.

> `To start using App Analytics, you must have the Admin, Finance, or Sales role in App Store Connect. You can access App Analytics by signing in to your App Store Connect account. For more information, see the Analytics and reporting overview in App Store Connect Help.`

[App Store Connect Resources and Help](https://itunespartner.apple.com/en/apps/faq/App%20Analytics_Overview)

**Comment by JanHalozan** [comment]
Closing, if the problem persists open a new issue.
