### ISSUE TITLE
Error logging in: Error: No account cookie :( Apple probably changed the login process

### ISSUE THREAD

**Issue by bassemyehia** [JanHalozan/iTunesConnectAnalytics#33]
i try to go to this URL
https://analytics.itunes.apple.com/analytics/api/v1

but it was not found can you update the your files with the new URL

**Comment by tdunham02** [comment]
> i try to go to this URL
> https://analytics.itunes.apple.com/analytics/api/v1
> 
> but it was not found can you update the your files with the new URL

Try this widget key (analytics.js line 14):

`e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42`

_Disclaimer: I created a library for App Analytics in PHP and this is the widget key I'm using, and my code is working as of today._

**Comment by JanHalozan** [comment]
I have tested it and the login still works just fine. Closing the issue. If you still have a problem please let me know.
