### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by msusur** [JanHalozan/iTunesConnectAnalytics#34]
Hey! 

First of all great job @JanHalozan ! I am working on a project that aggregates the analytics data from different platforms for my podcast.

I was wondering is this project still active? If so, are you accepting any new pull requests? I would love to convert this to promises, it would make my life much easier.
Thanks!

**Comment by JanHalozan** [comment]
Hi @msusur , it's still active. I've been a bit busy lately and haven't gotten around to reviewing and fixing issues here but I still plan on taking this further as long as it's useful to people.

**Comment by msusur** [comment]
That's great news, I'll look at it when I have time! Thanks @JanHalozan !!
