### ISSUE TITLE
Error after password change

### ISSUE THREAD

**Issue by fredchettouh** [JanHalozan/iTunesConnectAnalytics#36]
I used the API for a few calls and then, since I was going to share my code, decided to change my password in itunes connect. After that I received the following error for example on the quickstart code. 

```
var itc = require('itunesconnectanalytics');
var Itunes = itc.Itunes;
var AnalyticsQuery = itc.AnalyticsQuery;

var username = 'MyUserName';
var password = 'MyPassWord';
var appId = '12345'; //Found in My Apps -> App -> Apple ID or read below on getting the app id.

var instance = new Itunes(username, password, {
  errorCallback: function(e) {
    console.log('Error logging in: ' + e);
  },
  successCallback: function(d) {
    console.log('Logged in');
  }
});


instance.getApps(function(error, data) {
  console.log(JSON.stringify(data, null, 2));
});

```

returns` Error: No account cookie :( Apple probably changed the login process`.

Same also occurs with a new or incorrect user name or password. Any ideas how to address this?

Thanks

**Comment by JanHalozan** [comment]
I'd say there is an issue with your login credentials. Try 0.5.0, it has better error logging.
