### ISSUE TITLE
Unicode output  when trying to get app units for the specified time interval

### ISSUE THREAD

**Issue by rituraj17** [JanHalozan/iTunesConnectAnalytics#37]
Hi,
I was trying out your node js package and is currently facing some issue such that after logging when I am trying to get the app units metrics it's giving me the output in Unicode.

Code:

```
var itc = require('itunesconnectanalytics');
var Itunes = itc.Itunes;
var AnalyticsQuery = itc.AnalyticsQuery;

var username = 'XXXXX';
var password = 'XXXX';
var appId = 'XXXX'; //Found in My Apps -> App -> Apple ID or read below on getting the app id.

var instance = new Itunes(username, password, {
  errorCallback: function(e) {
    console.log('Error logging in: ' + e);
  },
  successCallback: function(d) {
    console.log('Logged in');
  }
});
var query = AnalyticsQuery.metrics(appId, {
    measures:  itc.measures.units,
  }).date('2018-04-10','2018-04-15');
  
  instance.request(query, function(error, result) {
    console.log(JSON.stringify(result, null, 2));
  });
```

Output:

```
Logged in
"\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000��AK\u0003A\f��Jȹ��\u0016�2G=\u0015�\"���C�����̘d\u0005Y����b=)x\f��K�\u001b0��!�Dtx6+�K*E-\u000b��\u0012{��9r�s�\u000b�X�N<��� �0ؙa�p\u0007A�g�t\u0006�Z0y\u0007:QH����*�\u001b�V��s\u0010����\\=Q+�ڳZe��콻8��F1������}6.�E�(���#���,PK\u001d���zݬ�����R�\u0012��Ŀ\"<R�g��;�x\u001c?\u0000F�3|�\u0001\u0000\u0000"
```

**Comment by aliaro428** [comment]
Also same issue for me as well did you get any fix?

**Comment by rituraj17** [comment]
> Also same issue for me as well did you get any fix?

I think its because you are using an incorrect iTunes credentials.
I was also facing the same issue so when I used the correct credentials it was working fine for me then.

@aliaro428  let me know if you are able to solve it. If not I'll be happy to help you to debug the error

**Comment by bassemyehia** [comment]
i got the same error but i use the right credentials can you help me out please?

**Comment by kopecms** [comment]
For me this output also appears when the time between requests is less than 10 second but could not be the case here

**Comment by bassemyehia** [comment]
I know this one so I make my code run 1 time for each application in about 15 sec

**Comment by kopecms** [comment]
How exactly are you creating query, what object are you passing to AnalyticsQuery.metrics? if you passing group parameter with empty object it also caused issues for me

**Comment by bassemyehia** [comment]
this is my entire code without cerd

var fs = require("fs");
var itc = require('./analytics.js');
var Itunes = itc.Itunes;
var AnalyticsQuery = itc.AnalyticsQuery;

var username = 'UserName';
var password = 'Password';
var appId = '824444355'; //Found in My Apps -> App -> Apple ID or read below on getting the app id.

var appsId = ['1033019299', '878147464', '923833518', '884749781', '824444355', '977130301', '865579070', '965763262', '1222419829', '629524578'];

var startDate = "2019-10-01";
var EndDate = "2019-10-31";
var filepath = "C:\\Users\\UserName\\AppData\\Local\\ketaby\\Apple\\";

function log(file, message) {
    //
    var fullfilelocation = filepath + file;
    //
    fs.writeFile(fullfilelocation, message, function (err) {
        if (err) {
            return console.log(err);
        }
        console.log("The file was saved!");
    });
    //console.log(message);
    //fs.createWriteStream(file)
    //fs.writeFileSync(file, message, 'utf8');
}

var instance = new Itunes(username, password, {
    errorCallback: function (e) {
        console.log('Error logging in: ' + e);
    },
    successCallback: function (d) {
        console.log('Logged in');

        //instance.getApps(function(error, data) {
        //  console.log(JSON.stringify(data, null, 2));
        //});

        //instance.getSettings(function(error, data) {
        // To get end date:
        // var end = data.configuration.dataEndDate;

        //  console.log(JSON.stringify(data, null, 2));
        //});

        //var query = new AnalyticsQuery.metrics(appId, {
        //	measures: [itc.measures.installs]
        //}).time(1, 'days');


        appsId.forEach(function (s) {
            // ... do something with s ...

            var query = AnalyticsQuery.metrics(s, {
                measures: itc.measures.units,
                group: {
                    //metric: itc.measures.installs, /* This is optional - it has to be one of the metric you add in measures above, else it will error. If you leave it blank, we'll default it to the first measures, which is normally what you need. */
                    dimension: itc.dimension.territory  /* this is the main thing you need to add when grouping */
                    //rank: "", /* Optional - not really sure how it works, but else leave it alone and we will default it to blank. TODO: Find out what this actually does */
                    //limit: 10 /* Optional - default is 200. TODO: Find out what this actually does */ 
                },
            }).date(startDate, EndDate);

            instance.request(query, function (error, result) {

                log(s + "_" + startDate.replace(/-/g, "_") + "_" + EndDate.replace(/-/g, "_") + '.json', JSON.stringify(result, null, 2))

                //console.log(JSON.stringify(result, null, 2));
            });


            setTimeout(function () {
                
            }, 15000);
            
            
        });
        
    }
});

**Comment by bassemyehia** [comment]
the new error i got now

Error logging in: Error: There was a problem with loading the login page cookies.

**Comment by kopecms** [comment]
new error: https://github.com/JanHalozan/iTunesConnectAnalytics/issues/38
JS is non blocking so it means that setTimeout as well as instance.request returns promises and code executes (there is no waiting when you call setTimeout). You call API endpoint for all apps almost at once so it causes problem. Read about async await syntax to make code more sequential or use .then and callbacks. Also be careful with forEach loop, it will not await for promises

**Comment by bassemyehia** [comment]
the error if finish now thanks for your time
