### ISSUE TITLE
Error logging in: Error: There was a problem with loading the login page cookies.

### ISSUE THREAD

**Issue by kopecms** [JanHalozan/iTunesConnectAnalytics#38]
For anybody facing title issue, please change:
https://olympus.itunes.apple.com/v1/session
to:
https://appstoreconnect.apple.com/olympus/v1/session
in analytics.js file

**Comment by LeoGtm** [comment]
I have this error since a couple of days. Switching the url didn't solve the issue :s

**Comment by JanHalozan** [comment]
Fixed in [0.4.4](https://github.com/JanHalozan/iTunesConnectAnalytics/releases/tag/v0.4.4).
