### ISSUE TITLE
Error logging in: Error: No account cookie :( Apple probably changed the login process

### ISSUE THREAD

**Issue by commit-master** [JanHalozan/iTunesConnectAnalytics#4]
Hey, 

I'm trying to use your wrapper but i can't make it work. I followed your installation guide but i get the above error.

Any idea on how i can fix this ?

thanks !

**Comment by JanHalozan** [comment]
Hi,
I just tried it and works with my account credentials so Apple didn't change anything (I was worried for a second there).

I tried to login using invalid credentials and I get the same error message so I'm assuming that you're providing invalid credentials. Try logging in directly [iTunesConnect](http://itunesconnect.apple.com) with the same credentials to make sure they're correct. If your problem persists let me know and we'll look in further.

**Comment by commit-master** [comment]
Ahaha sorry to make you scared, but I had a ' in my password and I didn't pay attention to this. Sorry about that ;)

**Comment by th0ress0n** [comment]
Error logging in: Error: No account cookie :( Apple probably changed the login process
I am getting the above error. I am able to log in through ITC with my credentials.
Any ideas why this is happening or if there is a fix for it at this time?
