### ISSUE TITLE
where can i find the provider ID?

### ISSUE THREAD

**Issue by lmk07** [JanHalozan/iTunesConnectAnalytics#45]
in appstore i have a multiple account, i just want to switch between the accounts, i found the providerId solution. but i dont knw where to find it. i just want to know where can i find the provider ID, thanks in advance.

**Comment by JanHalozan** [comment]
Should be the Team ID. Instructions on how to obtain it are [here](https://www.mobiloud.com/help/knowledge-base/ios-app-transfer/).
