### ISSUE TITLE
iTunes Connect has changed Session API

### ISSUE THREAD

**Issue by lbthanh** [JanHalozan/iTunesConnectAnalytics#8]
Before you can use 
1. https://idmsa.apple.com/appleauth/auth/signin
2. https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa?

Now
1. https://idmsa.apple.com/appleauth/auth/signin
2. https://olympus.itunes.apple.com/v1/session

**Comment by JanHalozan** [comment]
Does the old one still work? Is the new flow the same as the old?

Will take a look but just trying to gather as much info as possible.

**Comment by JanHalozan** [comment]
Fixed.
